name: Healthcheck Test Run

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node install
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run all tests
        run: npm run test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report
          path: jest_html_reporters.html
          retention-days: 30
