name: Manual Test Run

on:
  workflow_dispatch:
    inputs:
      TEST_NAMES:
        description: "Test/s names to run"
        default: ""

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node install
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run test/s
        run: npm run test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: html-report
          path: html-report
          retention-days: 30

